import { useEffect, useState } from "react";
import type { AdminUser } from "../types";
import { apiJson } from "../adminApi";
import { mediaUrl } from "../media";

export function AdminManagement(){
 const [admins,setAdmins]=useState<AdminUser[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState<AdminUser|null>(null); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false);
 const load=async()=>{try{setLoading(true);const d=await apiJson<{admins:AdminUser[]}>("/api/admins.php?action=list");setAdmins(d.admins||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Admin list load করা যায়নি।");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const remove=async(id:number)=>{if(!confirm("এই admin account মুছে ফেলতে চান?"))return;try{await apiJson("/api/admins.php?action=delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});await load();}catch(e){setError(e instanceof Error?e.message:"Admin delete করা যায়নি।");}};
 return <section className="admin-module"><div className="admin-module-header"><div><span className="admin-kicker">SUPER ADMIN</span><h1>Admin Management</h1><p>সব Admin-এর list, role, access status এবং account management এখান থেকে পরিচালনা করুন।</p></div><button className="admin-primary-button" type="button" onClick={()=>{setEditing(null);setShowForm(true)}}>＋ Admin Add করুন</button></div>
 {error&&<div className="admin-login-error">{error}</div>}
 <div className="admin-admins-card admin-form-card"><div className="admin-admin-summary"><span>মোট Admin <strong>{admins.length}</strong></span><span>Active <strong>{admins.filter(a=>a.is_active).length}</strong></span><span>Super Admin <strong>{admins.filter(a=>a.role==='super_admin').length}</strong></span></div>
 {loading?<div className="admin-settings-loading">Admin list load হচ্ছে...</div>:<div className="admin-admin-list">{admins.map(admin=><article className="admin-admin-item" key={admin.id}><span className="admin-admin-avatar">{admin.avatar_path?<img src={mediaUrl(admin.avatar_path)} alt={admin.name}/>:admin.name.slice(0,1)}</span><div className="admin-admin-info"><div className="admin-admin-title"><strong>{admin.name}</strong><span className={`admin-role-badge ${admin.role}`}>{admin.role==='super_admin'?'Super Admin':'Admin'}</span><span className={`admin-status-badge ${admin.is_active?'active':'inactive'}`}>{admin.is_active?'Active':'Inactive'}</span></div><p>{admin.email}{admin.phone?` • ${admin.phone}`:""}</p><small>Last login: {admin.last_login_at||"—"}</small></div><div className="admin-admin-actions"><button type="button" onClick={()=>{setEditing(admin);setShowForm(true)}}>Access / Edit</button><button className="danger" type="button" disabled={admins.length<=1} onClick={()=>remove(admin.id)}>Remove</button></div></article>)}</div>}
 </div>{showForm&&<AdminForm admin={editing} onClose={()=>setShowForm(false)} onSaved={()=>{setShowForm(false);load();}}/>}</section>
}

function AdminForm({admin,onClose,onSaved}:{admin:AdminUser|null;onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState({name:admin?.name||"",email:admin?.email||"",phone:admin?.phone||"",password:"",role:admin?.role||"admin",is_active:admin?.is_active??true}); const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const body:any={...form,id:admin?.id};if(!admin&& !form.password)throw new Error("Password দিতে হবে।");if(admin&&!form.password)delete body.password;await apiJson(`/api/admins.php?action=${admin?'update':'create'}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});onSaved();}catch(e){setError(e instanceof Error?e.message:"Admin save করা যায়নি।");}finally{setSaving(false);}};
 return <div className="admin-modal-backdrop"><form className="admin-form-card admin-admin-modal" onSubmit={submit}><div className="admin-image-picker-modal-header"><div><span className="admin-kicker">{admin?'EDIT ADMIN':'NEW ADMIN'}</span><h3>{admin?'Admin Access / Edit':'নতুন Admin তৈরি করুন'}</h3></div><button className="admin-modal-close" type="button" onClick={onClose}>×</button></div>{error&&<div className="admin-login-error">{error}</div>}<div className="admin-form-grid"><label>নাম *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email *<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as any})}><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select></label><label>Password {admin?'(নতুন হলে দিন)':'*'}<input type="password" minLength={8} required={!admin} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="admin-settings-checkbox"><span>Access Status</span><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label></div><div className="admin-form-actions"><button className="admin-secondary-button" type="button" onClick={onClose}>Cancel</button><button className="admin-primary-button" disabled={saving}>{saving?'সংরক্ষণ হচ্ছে...':'Save Admin'}</button></div></form></div>;
}
