import { useEffect, useMemo, useState } from "react";
import { apiJson, postJson } from "../adminApi";
import { bloodGroups } from "../data";

type Donor = { id:number; name:string; blood_group:string; phone:string; area:string; last_donation_date:string|null; donation_count:number; assigned_at?:string };
type R = { id:number; patient_name:string; blood_group:string; contact_phone:string; hospital:string; location:string; required_date:string|null; units_needed:number; details:string; status:"pending"|"approved"|"fulfilled"|"cancelled"; selected_donors:Donor[]; selected_count:number };
const label=(s:R["status"])=>({pending:"অপেক্ষমাণ",approved:"অনুমোদিত",fulfilled:"সম্পন্ন",cancelled:"বাতিল"}[s]);

export function BloodRequestsManagement(){
 const [rows,setRows]=useState<R[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[group,setGroup]=useState("all"),[status,setStatus]=useState("all");
 const [modal,setModal]=useState<{request:R;available:Donor[];selected:Donor[]}|null>(null),[modalLoading,setModalLoading]=useState(false),[selectedDonor,setSelectedDonor]=useState<Donor|null>(null),[busy,setBusy]=useState(false);
 const load=async()=>{try{setLoading(true);const d=await apiJson<{requests:R[]}>("/api/blood.php?action=requests");setRows(d.requests||[])}catch(e){setError(e instanceof Error?e.message:"আবেদন লোড করা যায়নি।")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const openDonors=async(r:R)=>{try{setError("");setModalLoading(true);const d=await apiJson<{request:R;available_donors:Donor[];selected_donors:Donor[]}>(`/api/blood.php?action=request-donor-options&request_id=${r.id}`);setModal({request:r,available:d.available_donors||[],selected:d.selected_donors||[]})}catch(e){setError(e instanceof Error?e.message:"Donor list লোড করা যায়নি।")}finally{setModalLoading(false)}};
 const chooseDonor=async()=>{if(!modal||!selectedDonor)return;try{setBusy(true);await postJson("/api/blood.php?action=assign-donor",{request_id:modal.request.id,donor_id:selectedDonor.id});setSelectedDonor(null);await openDonors(modal.request);await load()}catch(e){setError(e instanceof Error?e.message:"Donor নির্বাচন করা যায়নি।")}finally{setBusy(false)}};
 const removeAssigned=async(requestId:number,donor:Donor)=>{if(!confirm(`${donor.name}-কে এই আবেদন থেকে সরাতে চান?`))return;try{setBusy(true);await postJson("/api/blood.php?action=remove-assigned-donor",{request_id:requestId,donor_id:donor.id});if(modal&&modal.request.id===requestId)await openDonors(modal.request);await load()}catch(e){setError(e instanceof Error?e.message:"Donor সরানো যায়নি।")}finally{setBusy(false)}};
 const update=async(id:number,s:R["status"])=>{try{setError("");if(s==="fulfilled")await postJson("/api/blood.php?action=fulfill-request",{id});else await postJson("/api/blood.php?action=request-status",{id,status:s});await load();if(modal&&modal.request.id===id){setModal(null);setSelectedDonor(null)}}catch(e){setError(e instanceof Error?e.message:"Status update করা যায়নি।")}};
 const remove=async(id:number)=>{if(!confirm("এই আবেদনটি মুছে ফেলতে চান?"))return;try{await postJson("/api/blood.php?action=delete-request",{id});await load()}catch(e){setError(e instanceof Error?e.message:"আবেদন মুছে ফেলা যায়নি।")}};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>(!q||[r.patient_name,r.contact_phone,r.hospital,r.location,r.blood_group].some(v=>String(v||"").toLowerCase().includes(q)))&&(group==="all"||r.blood_group===group)&&(status==="all"||r.status===status))},[rows,search,group,status]);
 const reset=()=>{setSearch("");setGroup("all");setStatus("all")};
 return <section className="admin-module">
  <div className="admin-module-header"><div><span className="admin-kicker">BLOOD SERVICE</span><h1>রক্তের আবেদন</h1><p>আবেদন পরিচালনা, প্রয়োজনীয় donor নির্বাচন এবং রক্তদান সম্পন্ন হওয়া ট্র্যাক করুন।</p></div><button className="admin-secondary-button" onClick={load}>↻ Refresh</button></div>
  {error&&<div className="admin-data-notice">{error}</div>}
  <div className="admin-form-card blood-donor-filters"><div className="blood-filter-heading"><div><span className="admin-kicker">FILTER</span><h2>আবেদন খুঁজুন</h2></div><button className="admin-secondary-button" type="button" onClick={reset}>Reset</button></div><div className="admin-form-grid blood-filter-grid"><label className="full">রোগী / মোবাইল / হাসপাতাল / স্থান / রক্তের গ্রুপ<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search করুন..."/></label><label>রক্তের গ্রুপ<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">সব গ্রুপ</option>{bloodGroups.map(g=><option key={g}>{g}</option>)}</select></label><label>Status<select className={status!=="all"?`blood-request-status-${status}`:""} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">সব status</option><option value="pending">অপেক্ষমাণ</option><option value="approved">অনুমোদিত</option><option value="fulfilled">সম্পন্ন</option><option value="cancelled">বাতিল</option></select></label></div><div className="blood-filter-result">{filtered.length}টি আবেদন দেখানো হচ্ছে</div></div>
  <div className="admin-form-card admin-table-card">{loading?<div className="admin-list-empty">আবেদন লোড হচ্ছে...</div>:filtered.length===0?<div className="admin-list-empty">এই filter অনুযায়ী কোনো আবেদন পাওয়া যায়নি।</div>:<div className="admin-table-wrap"><table className="admin-table blood-request-table"><thead><tr><th>রোগী</th><th>রক্ত</th><th>যোগাযোগ</th><th>হাসপাতাল/স্থান</th><th>তারিখ</th><th>ব্যাগ</th><th>নির্বাচিত donor</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>
   <td><strong>{r.patient_name}</strong><small>{r.details||""}</small></td><td><b className="blood-badge">{r.blood_group}</b></td><td>{r.contact_phone}</td><td>{r.hospital||"-"}<small>{r.location||""}</small></td><td>{r.required_date||"-"}</td><td><b>{r.units_needed}</b></td>
   <td><div className="selected-donor-cell">{r.selected_donors?.length?r.selected_donors.map(d=><span className="selected-donor-chip" key={d.id}>{d.name}<button type="button" title="Donor সরান" onClick={()=>removeAssigned(r.id,d)}>×</button></span>):<span className="no-donor">এখনও নির্বাচন হয়নি</span>}{r.status==="pending"&&r.selected_count<r.units_needed&&<button className="donor-select-button" onClick={()=>openDonors(r)}>+ Donor নির্বাচন</button>}</div></td>
   <td><select className={`blood-status-select blood-request-status-${r.status}`} value={r.status} onChange={e=>update(r.id,e.target.value as R["status"])}>{["pending","approved","fulfilled","cancelled"].map(s=><option key={s} value={s}>{label(s as R["status"])}</option>)}</select></td>
   <td><button className="table-danger" onClick={()=>remove(r.id)}>Delete</button></td>
  </tr>)}</tbody></table></div>}</div>

  {modal&&<div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setModal(null);setSelectedDonor(null)}}}><div className="blood-donor-picker-modal" role="dialog" aria-modal="true">
   <div className="admin-image-picker-modal-header"><div><span className="admin-kicker">DONOR SELECTION</span><h3>{modal.request.blood_group} রক্তের জন্য donor নির্বাচন</h3><p>{modal.request.patient_name} · প্রয়োজন {modal.request.units_needed} bag · নির্বাচিত {modal.selected.length} জন</p></div><button className="admin-modal-close" onClick={()=>{setModal(null);setSelectedDonor(null)}}>×</button></div>
   <div className="donor-picker-progress"><strong>{modal.selected.length}/{modal.request.units_needed} জন নির্বাচিত</strong><span>এক bag-এর জন্য একজন donor</span></div>
   {modal.selected.length>0&&<div className="selected-donor-list"><h4>নির্বাচিত donor</h4>{modal.selected.map(d=><div className="selected-donor-row" key={d.id}><div><strong>{d.name}</strong><small>{d.phone} · {d.area||"এলাকা নেই"}</small></div><button className="table-danger" disabled={busy} onClick={()=>removeAssigned(modal.request.id,d)}>সরান</button></div>)}</div>}
   {modal.selected.length>=modal.request.units_needed?<div className="donor-picker-complete">✓ প্রয়োজনীয় সংখ্যক donor নির্বাচন সম্পন্ন হয়েছে। এখন রক্তদান হলে Status থেকে <b>সম্পন্ন</b> নির্বাচন করুন।</div>:<><h4 className="donor-picker-title">উপলভ্য {modal.request.blood_group} donor</h4>{modalLoading?<div className="admin-list-empty">Donor list লোড হচ্ছে...</div>:modal.available.length===0?<div className="donor-picker-empty">এই মুহূর্তে এই blood group-এর কোনো available donor নেই।</div>:<div className="donor-picker-grid">{modal.available.map(d=><button className="donor-picker-card" key={d.id} onClick={()=>setSelectedDonor(d)}><span className="blood-badge">{d.blood_group}</span><strong>{d.name}</strong><small>📞 {d.phone}</small><small>📍 {d.area||"এলাকা নেই"}</small><small>শেষ রক্তদান: {d.last_donation_date||"কখনও দেননি"} · {d.donation_count??0} বার</small></button>)}</div>}</>}
   {selectedDonor&&<div className="donor-confirm-box"><div><span className="admin-kicker">CONFIRM BEFORE SELECT</span><h4>{selectedDonor.name}</h4><p>📞 {selectedDonor.phone} · 📍 {selectedDonor.area||"এলাকা নেই"}</p><p>শেষ রক্তদান: {selectedDonor.last_donation_date||"কখনও দেননি"} · মোট {selectedDonor.donation_count??0} বার</p></div><div className="donor-confirm-actions"><a href={`tel:${selectedDonor.phone}`} className="donor-call-button">☎ ফোন করুন</a><button className="admin-primary-button" disabled={busy} onClick={chooseDonor}>ফোনে নিশ্চিত হয়েছে — Select করুন</button><button className="admin-secondary-button" disabled={busy} onClick={()=>setSelectedDonor(null)}>বাতিল</button></div></div>}
  </div></div>}
 </section>;
}
