<?php
require_once __DIR__.'/helpers.php'; require_once __DIR__.'/db.php'; allow_cors();
$config=require __DIR__.'/config.php'; session_name($config['app']['session_name']??'shanti_sangha_admin'); session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'httponly'=>true,'samesite'=>'Lax']); session_start();
function about_admin():void{if(empty($_SESSION['admin_id']))send_json(['success'=>false,'message'=>'Authentication required.'],401);}
function about_bool($v):int{return in_array(strtolower((string)$v),['1','true','yes','on'],true)?1:0;}
function about_payload():array{$d=json_decode(file_get_contents('php://input'),true);return is_array($d)?$d:[];}
$action=$_GET['action']??'list';
try{$pdo=db();$has=(int)$pdo->query('SELECT COUNT(*) FROM about_sections')->fetchColumn();if($has===0){$seed=$pdo->prepare('INSERT INTO about_sections(title,description,sort_order,is_published) VALUES(?,?,?,1)');foreach([['আমাদের লক্ষ্য','মানবিকতা, স্বেচ্ছাসেবা ও সামাজিক দায়বদ্ধতার মাধ্যমে মানুষের পাশে দাঁড়ানো এবং একটি সুন্দর সমাজ গড়ে তোলা আমাদের লক্ষ্য।',1],['আমাদের কার্যক্রম','বৃক্ষরোপণ, খাদ্য ও ইফতার সামগ্রী বিতরণ, সামাজিক আয়োজন, রক্ত সেবা এবং প্রয়োজনীয় মানুষের পাশে দাঁড়ানোর মতো কার্যক্রম পরিচালনা করা হয়।',2],['আমাদের মূল্যবোধ','সততা, সহমর্মিতা, পারস্পরিক সহযোগিতা এবং স্বেচ্ছাসেবার মানসিকতাকে আমরা গুরুত্ব দিই।',3]] as $item)$seed->execute($item);}
 if($action==='list'&&$_SERVER['REQUEST_METHOD']==='GET')send_json(['success'=>true,'sections'=>$pdo->query('SELECT * FROM about_sections WHERE is_published=1 ORDER BY sort_order ASC,id ASC')->fetchAll()]);
 about_admin();
 if($action==='admin-list'&&$_SERVER['REQUEST_METHOD']==='GET')send_json(['success'=>true,'sections'=>$pdo->query('SELECT * FROM about_sections ORDER BY sort_order ASC,id ASC')->fetchAll()]);
 if($action==='create'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=about_payload();$title=trim((string)($p['title']??''));if($title==='')send_json(['success'=>false,'message'=>'শিরোনাম দিন।'],422);$s=$pdo->prepare('INSERT INTO about_sections(title,description,sort_order,is_published) VALUES(?,?,?,?)');$s->execute([$title,trim((string)($p['description']??'')),(int)($p['sort_order']??0),about_bool($p['is_published']??0)]);send_json(['success'=>true,'message'=>'About section যোগ হয়েছে।','id'=>(int)$pdo->lastInsertId()],201);}
 if($action==='update'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=about_payload();$id=(int)($p['id']??0);$title=trim((string)($p['title']??''));if($id<1||$title==='')send_json(['success'=>false,'message'=>'ID ও শিরোনাম প্রয়োজন।'],422);$s=$pdo->prepare('UPDATE about_sections SET title=?,description=?,sort_order=?,is_published=? WHERE id=?');$s->execute([$title,trim((string)($p['description']??'')),(int)($p['sort_order']??0),about_bool($p['is_published']??0),$id]);send_json(['success'=>true,'message'=>'About section আপডেট হয়েছে।']);}
 if($action==='delete'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=about_payload();$s=$pdo->prepare('DELETE FROM about_sections WHERE id=?');$s->execute([(int)($p['id']??0)]);if(!$s->rowCount())send_json(['success'=>false,'message'=>'Section পাওয়া যায়নি।'],404);send_json(['success'=>true,'message'=>'About section মুছে ফেলা হয়েছে।']);}
 send_json(['success'=>false,'message'=>'Invalid about request.'],405);
}catch(Throwable $e){send_json(['success'=>false,'message'=>'About content পরিচালনা করা যায়নি।'],503);}
