<?php
require_once __DIR__.'/helpers.php'; require_once __DIR__.'/db.php'; allow_cors();
$config=require __DIR__.'/config.php'; session_name($config['app']['session_name']??'shanti_sangha_admin'); session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'httponly'=>true,'samesite'=>'Lax']); session_start();
function gallery_admin():void{if(empty($_SESSION['admin_id']))send_json(['success'=>false,'message'=>'Authentication required.'],401);}
function gallery_bool($v):int{return in_array(strtolower((string)$v),['1','true','yes','on'],true)?1:0;}
function gallery_payload():array{$d=json_decode(file_get_contents('php://input'),true);return is_array($d)?$d:[];}
function upload_gallery_file():?string{if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)return null;$max=max(1,min(50,(int)get_site_setting('upload_max_size_mb','8')));if($_FILES['file']['size']>$max*1024*1024)send_json(['success'=>false,'message'=>'ছবির সর্বোচ্চ আকার '.$max.' MB।'],422);$formatList=array_values(array_filter(array_map('strtolower',array_map('trim',explode(',',get_site_setting('upload_allowed_formats','jpg,png,webp,gif'))))));$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];$allowed=array_filter($allowed,fn($ext)=>in_array($ext,$formatList,true));$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['file']['tmp_name']);if(!isset($allowed[$mime]))send_json(['success'=>false,'message'=>'এই image format বর্তমানে অনুমোদিত নয়।'],422);$dir=dirname(__DIR__).'/uploads/gallery';if(!is_dir($dir)&&!mkdir($dir,0755,true))send_json(['success'=>false,'message'=>'Upload folder তৈরি করা যায়নি।'],503);$name=bin2hex(random_bytes(10)).'-'.time().'.'.$allowed[$mime];if(!move_uploaded_file($_FILES['file']['tmp_name'],$dir.'/'.$name))send_json(['success'=>false,'message'=>'ছবি আপলোড করা যায়নি।'],503);return '/uploads/gallery/'.$name;}
$action=$_GET['action']??'list';
try{$pdo=db();
 if($action==='list'&&$_SERVER['REQUEST_METHOD']==='GET'){send_json(['success'=>true,'gallery'=>$pdo->query('SELECT * FROM gallery WHERE is_published=1 ORDER BY sort_order ASC,id DESC')->fetchAll()]);}
 gallery_admin();
 if($action==='admin-list'&&$_SERVER['REQUEST_METHOD']==='GET'){send_json(['success'=>true,'gallery'=>$pdo->query('SELECT * FROM gallery ORDER BY sort_order ASC,id DESC')->fetchAll()]);}
 if($action==='create'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=isset($_POST['title'])||isset($_FILES['file'])?$_POST:gallery_payload();$path=upload_gallery_file()?:trim((string)($p['file_path']??''));if($path==='')send_json(['success'=>false,'message'=>'একটি ছবি path অথবা file দিতে হবে।'],422);$s=$pdo->prepare('INSERT INTO gallery(title,caption,media_type,file_path,thumbnail_path,category,is_published,sort_order) VALUES(?,?,?,?,?,?,?,?)');$s->execute([trim((string)($p['title']??'')),trim((string)($p['caption']??'')),'image',$path,trim((string)($p['thumbnail_path']??'')),trim((string)($p['category']??'')),gallery_bool($p['is_published']??0),(int)($p['sort_order']??0)]);send_json(['success'=>true,'message'=>'গ্যালারিতে ছবি যোগ হয়েছে।','id'=>(int)$pdo->lastInsertId()],201);}
 if($action==='update'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=isset($_POST['id'])?$_POST:gallery_payload();$id=(int)($p['id']??0);if($id<1)send_json(['success'=>false,'message'=>'Gallery item ID প্রয়োজন।'],422);$old=$pdo->prepare('SELECT file_path FROM gallery WHERE id=?');$old->execute([$id]);$oldPath=$old->fetchColumn();$path=upload_gallery_file()?:trim((string)($p['file_path']??$oldPath));$s=$pdo->prepare('UPDATE gallery SET title=?,caption=?,file_path=?,thumbnail_path=?,category=?,is_published=?,sort_order=? WHERE id=?');$s->execute([trim((string)($p['title']??'')),trim((string)($p['caption']??'')),$path,trim((string)($p['thumbnail_path']??'')),trim((string)($p['category']??'')),gallery_bool($p['is_published']??0),(int)($p['sort_order']??0),$id]);send_json(['success'=>true,'message'=>'গ্যালারির তথ্য আপডেট হয়েছে।']);}
 if($action==='delete'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=gallery_payload();$id=(int)($p['id']??0);$s=$pdo->prepare('DELETE FROM gallery WHERE id=?');$s->execute([$id]);if(!$s->rowCount())send_json(['success'=>false,'message'=>'ছবিটি পাওয়া যায়নি।'],404);send_json(['success'=>true,'message'=>'ছবিটি মুছে ফেলা হয়েছে।']);}
 send_json(['success'=>false,'message'=>'Invalid gallery request.'],405);
}catch(Throwable $e){send_json(['success'=>false,'message'=>'Gallery operation সম্পন্ন করা যায়নি।'],503);}
