<?php
require_once __DIR__.'/helpers.php'; require_once __DIR__.'/db.php'; allow_cors();
$config=require __DIR__.'/config.php'; session_name($config['app']['session_name']??'shanti_sangha_admin'); session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'httponly'=>true,'samesite'=>'Lax']); session_start();
function member_payload():array{$d=json_decode(file_get_contents('php://input'),true);return is_array($d)?$d:[];} function member_admin():void{if(empty($_SESSION['admin_id']))send_json(['success'=>false,'message'=>'Authentication required.'],401);}
$action=$_GET['action']??'';try{$pdo=db();
 if($action==='apply'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=member_payload();foreach(['name','phone','address','blood_group'] as $k){if(trim((string)($p[$k]??''))==='')send_json(['success'=>false,'message'=>'প্রয়োজনীয় তথ্য পূরণ করুন।'],422);}$s=$pdo->prepare('INSERT INTO membership_applications(name,phone,email,address,father_name,mother_name,profession,blood_group,message) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([trim((string)$p['name']),trim((string)$p['phone']),trim((string)($p['email']??'')),trim((string)$p['address']),trim((string)($p['father_name']??'')),trim((string)($p['mother_name']??'')),trim((string)($p['profession']??'')),trim((string)$p['blood_group']),trim((string)($p['message']??''))]);$memberId=(int)$pdo->lastInsertId();if(get_site_setting('notify_member_application','1')==='1')create_notification($pdo,'member','নতুন সদস্য আবেদন',trim((string)$p['name']).' নতুন সদস্য হওয়ার জন্য আবেদন করেছেন।','member',$memberId);send_json(['success'=>true,'message'=>'সদস্য আবেদন সফলভাবে পাঠানো হয়েছে।'],201);}
 member_admin();
 if($action==='list'&&$_SERVER['REQUEST_METHOD']==='GET')send_json(['success'=>true,'applications'=>$pdo->query('SELECT * FROM membership_applications ORDER BY created_at DESC,id DESC')->fetchAll()]);
 if($action==='status'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=member_payload();$st=(string)($p['status']??'');if(!in_array($st,['pending','approved','rejected'],true))send_json(['success'=>false,'message'=>'Invalid status.'],422);$q=$pdo->prepare('UPDATE membership_applications SET status=? WHERE id=?');$q->execute([$st,(int)($p['id']??0)]);log_admin_activity($pdo,'Members','status','সদস্য আবেদনের status পরিবর্তন করে '.$st.' করা হয়েছে।',(int)($p['id']??0));send_json(['success'=>true,'message'=>'সদস্য আবেদনের status আপডেট হয়েছে।']);}
 if($action==='delete'&&$_SERVER['REQUEST_METHOD']==='POST'){$p=member_payload();$q=$pdo->prepare('DELETE FROM membership_applications WHERE id=?');$q->execute([(int)($p['id']??0)]);log_admin_activity($pdo,'Members','delete','সদস্য আবেদন মুছে ফেলা হয়েছে।',(int)($p['id']??0));send_json(['success'=>true,'message'=>'সদস্য আবেদন মুছে ফেলা হয়েছে।']);}
 send_json(['success'=>false,'message'=>'Invalid member request.'],405);
}catch(Throwable $e){send_json(['success'=>false,'message'=>'সদস্য আবেদন পরিচালনা করা যায়নি।'],503);}
